### ISSUE TITLE
其实你可以用json.dump来输出数据，然后写个php再过滤数据然后存入数据库

### ISSUE THREAD

**Issue by ghost** [521xueweihan/PySpider#1]
[GithubAGSearch.py.zip](https://github.com/521xueweihan/PySpider/files/1276019/GithubAGSearch.py.zip)
附上一个我的github repo爬虫

**Comment by 521xueweihan** [comment]
代理爬虫的项目优秀的项目已经很多了，我的这个项目就不维护了（精力有限），当作一个demo项目看待吧。😅
